server:
  port: 8087

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authenticate/**

        - id: user-profile
          uri: lb://user-profile
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: treatment-service
          uri: lb://treatment-service
          predicates:
            - Path=/treatments/**
          filters:
            - AuthenticationFilter

        - id: bookmark-service
          uri: lb://bookmark-service
          predicates:
            - Path=/bookmarks/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}  # Supports both Docker & Local Windows

  instance:
    hostname: api-gateway

# Disable Spring Cloud Config (Enable when needed)
spring.cloud.config.enabled: false

# Actuator Endpoints for Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
