server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api_gateway_service
  cloud:
    gateway:
      routes:
        - id: authentication_service
          uri: lb://authentication_service
          predicates:
            - Path=/authenticate/**

        - id: user_profile_service  # User Service
          uri: lb://user_profile_service
          predicates:
            - Path=/users/**

        - id: treatment_service  # Treatment Service
          uri: lb://treatment_service
          predicates:
            - Path=/treatments/**
          filters:
            - AuthenticationFilter

        - id: bookmark_service  # Bookmark Service
          uri: lb://bookmark_service
          predicates:
            - Path=/bookmarks/**
          filters:
            - AuthenticationFilter
